[build]
  command = "npm run build && npm run build:client"
  publish = "dist/public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
